//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `MumbleServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sgvn.mumblepoc.ice;

/** @hidden */
public class _MetaCallbackPrxI extends com.zeroc.Ice._ObjectPrxI implements MetaCallbackPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
