//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `MumbleServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sgvn.mumblepoc.ice;

/**
 * This is thrown when you supply an invalid callback.
 **/
public class InvalidCallbackException extends MurmurException
{
    public InvalidCallbackException()
    {
        super();
    }

    public InvalidCallbackException(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::MumbleServer::InvalidCallbackException";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::MumbleServer::InvalidCallbackException", -1, false);
        ostr_.endSlice();
        super._writeImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
        super._readImpl(istr_);
    }

    /** @hidden */
    public static final long serialVersionUID = -1821661843568238381L;
}
