//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.9
//
// <auto-generated>
//
// Generated from file `MumbleServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sgvn.mumblepoc.ice;

/**
 * This is thrown when the channel operation would exceed the channel nesting limit
 **/
public class NestingLimitException extends MurmurException
{
    public NestingLimitException()
    {
        super();
    }

    public NestingLimitException(Throwable cause)
    {
        super(cause);
    }

    public String ice_id()
    {
        return "::MumbleServer::NestingLimitException";
    }

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::MumbleServer::NestingLimitException", -1, false);
        ostr_.endSlice();
        super._writeImpl(ostr_);
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
        super._readImpl(istr_);
    }

    /** @hidden */
    public static final long serialVersionUID = 1941353367418222418L;
}
